management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 5555
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    baseservice: /base/**
    socialservice: /social/**
  # ignored-services: 'baseservice, socialservice'
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.example.zuulserver: INFO

hystrix:
  command:
    default:
      excution.isolation.thread.timeoutInMilliseconds: 1000


